# fly.toml app configuration file generated for deploy-express on 2023-08-20T12:22:41-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "deploy-express"
primary_region = "lax"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
